// 50 phones, 1992–2026. One scrub continuum, seven paced chapters.
// Headline = one idea. eli5 = one sentence. demo = the product of that stop.
window.CHAPTERS = [
  { id: "pocket",   sec: "0.1", name: "POCKET",   from: 0,  until: 2,  years: "1992" },
  { id: "candybar", sec: "0.2", name: "CANDYBAR", from: 2,  until: 7,  years: "1999" },
  { id: "thin",     sec: "0.3", name: "THIN",     from: 7,  until: 12, years: "2004" },
  { id: "glass",    sec: "0.4", name: "GLASS",    from: 12, until: 23, years: "2007" },
  { id: "everyone", sec: "0.5", name: "EVERYONE", from: 23, until: 33, years: "2012" },
  { id: "edge",     sec: "0.6", name: "EDGE",     from: 33, until: 43, years: "2017" },
  { id: "island",   sec: "0.7", name: "ISLAND",   from: 43, until: 50, years: "2022" }
];

window.PHONES = [
  { id: "1992-microtac", year: 1992, name: "Motorola MicroTAC", era: "brick", chapter: "pocket",
    feature: "flip_mouthpiece", demo: "flip_mouthpiece", label: "The flip is born",
    eli5: "A mouthpiece that folds down. Pocketable, finally.",
    specs: ["Flip-down mouthpiece", "Red LED display", "Nickel-cadmium battery"],
    materials: "Charcoal ABS, pull-up antenna, first truly pocketable cellphone." },
  { id: "1996-starTAC", year: 1996, name: "Motorola StarTAC", era: "flip", chapter: "pocket",
    feature: "clamshell", demo: "clamshell", label: "First clamshell",
    eli5: "The first true clamshell. Flip it shut.",
    specs: ["Clamshell fold", "Vibrate alert", "~88 g"],
    materials: "Magnesium-grey shell — flip became a status symbol." },
  { id: "1999-3310", year: 1999, name: "Nokia 3310", era: "candybar", chapter: "candybar",
    feature: "snake", demo: "snake", label: "Indestructible",
    eli5: "The brick that wouldn't die. Snake is the product.",
    specs: ["Snake II", "Xpress-on covers", "Monochrome LCD"],
    materials: "Bombproof polycarbonate. 126 million sold." },
  { id: "2000-6210", year: 2000, name: "Nokia 6210", era: "candybar", chapter: "candybar",
    feature: "sms", demo: "t9", label: "Texting machine",
    eli5: "Predictive text. Thumbs wrote the 2000s.",
    specs: ["T9 predictive text", "WAP browser", "Infrared"],
    materials: "Slim dark-green candybar — the business texter's favourite." },
  { id: "2002-3650", year: 2002, name: "Nokia 3650", era: "candybar", chapter: "candybar",
    feature: "camera_circle_pad", demo: "rotary_keys", label: "Circular keypad",
    eli5: "A camera with a rotary pad. Weird on purpose.",
    specs: ["Built-in camera", "Rotary keypad", "Symbian S60"],
    materials: "Playful pod with an unmistakable round dial." },
  { id: "2002-treo", year: 2002, name: "Palm Treo 180", era: "pda", chapter: "candybar",
    feature: "stylus", demo: "stylus", label: "PDA meets phone",
    eli5: "A PDA that makes calls. Tap with a stylus.",
    specs: ["Palm OS", "QWERTY thumbboard", "Stylus + touch"],
    materials: "Grey hybrid — tap the resistive screen." },
  { id: "2003-6600", year: 2003, name: "Nokia 6600", era: "candybar", chapter: "candybar",
    feature: "symbian", demo: "appgrid", label: "Symbian smartphone",
    eli5: "Apps on a pebble. Symbian for everyone.",
    specs: ["Symbian S60", "VGA camera", "65k colour screen"],
    materials: "Rounded pebble — an early app phone for the masses." },
  { id: "2004-razr", year: 2004, name: "Motorola RAZR V3", era: "flip", chapter: "thin",
    feature: "flip_animation", demo: "flip_animation", label: "Impossibly thin",
    eli5: "Aircraft aluminium, 14 mm. The flip is the whole point.",
    specs: ["14 mm thin", "Etched metal keypad", "Anodised aluminium"],
    materials: "The mid-2000s icon. Flip it open." },
  { id: "2004-n-gage", year: 2004, name: "Nokia N-Gage", era: "gaming", chapter: "thin",
    feature: "side_talk", demo: "sidetalk", label: "Game deck phone",
    eli5: "A game deck you hold like a taco.",
    specs: ["Game cartridges", "Side-talking", "Symbian S60"],
    materials: "The taco — hold it sideways to your ear." },
  { id: "2005-sidekick", year: 2005, name: "T-Mobile Sidekick II", era: "slider", chapter: "thin",
    feature: "swing_screen", demo: "swing_screen", label: "Swivel screen",
    eli5: "Flick the screen. The keyboard was the point.",
    specs: ["Swivel display", "QWERTY", "Always-on data"],
    materials: "Beloved by texters — swing to type." },
  { id: "2006-chocolate", year: 2006, name: "LG Chocolate", era: "slider", chapter: "thin",
    feature: "slide_keys", demo: "slider", label: "Touch-glow slider",
    eli5: "Glossy black. Touch keys that glow red.",
    specs: ["Touch-sensitive keys", "Slide-up form", "Music focus"],
    materials: "Black slab, red capacitive glow." },
  { id: "2006-n95", year: 2006, name: "Nokia N95", era: "slider", chapter: "thin",
    feature: "slide_camera", demo: "twoway_slider", label: "Multimedia computer",
    eli5: "A computer that slides two ways.",
    specs: ["5 MP Carl Zeiss", "Two-way slide", "GPS + Wi-Fi"],
    materials: "Dual-slider: media up, keypad down." },
  { id: "2007-iphone", year: 2007, name: "iPhone (1st gen)", era: "smartphone", chapter: "glass",
    feature: "homescreen", demo: "springboard", label: "Multitouch begins",
    eli5: "No stylus. Your finger is the pointer.",
    specs: ["Multitouch glass", "One home button", "Visual voicemail"],
    materials: "Aluminium + glass. Tap the icons." },
  { id: "2007-curve", year: 2007, name: "BlackBerry Curve 8300", era: "qwerty", chapter: "glass",
    feature: "trackball_bbm", demo: "bbm", label: "Trackball + BBM",
    eli5: "D means delivered. R means read.",
    specs: ["Pearl trackball", "Full QWERTY", "Push email"],
    materials: "The messaging machine." },
  { id: "2008-g1", year: 2008, name: "HTC Dream (G1)", era: "android", chapter: "glass",
    feature: "slide_qwerty", demo: "slide_qwerty", label: "First Android",
    eli5: "The first Android. Slide out a real keyboard.",
    specs: ["Android 1.0", "Slide QWERTY", "Trackball"],
    materials: "Slide the keyboard. History starts." },
  { id: "2008-bold", year: 2008, name: "BlackBerry Bold 9000", era: "qwerty", chapter: "glass",
    feature: "optical_trackpad", demo: "bbm", label: "Business icon",
    eli5: "Push email. The boardroom in your pocket.",
    specs: ["Sharp QWERTY", "Leatherette back", "3G + Wi-Fi"],
    materials: "Chrome-framed status symbol." },
  { id: "2009-pre", year: 2009, name: "Palm Pre", era: "webos", chapter: "glass",
    feature: "card_multitask", demo: "webos_cards", label: "Cards multitasking",
    eli5: "Cards, not apps. Flick one away to quit.",
    specs: ["webOS", "Card multitasking", "Slide keyboard"],
    materials: "Pebble-smooth. Swipe a card to close it." },
  { id: "2009-droid", year: 2009, name: "Motorola Droid", era: "android", chapter: "glass",
    feature: "slide_keyboard", demo: "slide_qwerty", label: "Droid does",
    eli5: "Android goes mainstream. Slide to type.",
    specs: ["Android 2.0", "Slide keyboard", "Google Maps Nav"],
    materials: "Industrial metal that made Android a US default." },
  { id: "2010-iphone4", year: 2010, name: "iPhone 4", era: "smartphone", chapter: "glass",
    feature: "retina_homescreen", demo: "springboard", label: "Retina display",
    eli5: "Pixels you cannot see. Glass on steel.",
    specs: ["Retina display", "Stainless frame", "FaceTime"],
    materials: "Glass sandwich on a steel band." },
  { id: "2010-n8", year: 2010, name: "Nokia N8", era: "symbian", chapter: "glass",
    feature: "xenon_flash", demo: "camera_shutter", label: "Xenon camera",
    eli5: "A real Xenon flash. Snap it.",
    specs: ["12 MP Xenon flash", "HDMI out", "Anodised aluminium"],
    materials: "Candy-coloured metal unibody." },
  { id: "2010-desire", year: 2010, name: "HTC Desire", era: "android", chapter: "glass",
    feature: "sense_ui", demo: "appgrid", label: "HTC Sense",
    eli5: "Sense UI. Android with a pulse.",
    specs: ["HTC Sense UI", "AMOLED screen", "Optical trackpad"],
    materials: "Soft-touch favourite with a flip-clock home." },
  { id: "2011-galaxy-s2", year: 2011, name: "Samsung Galaxy S II", era: "android", chapter: "glass",
    feature: "touchwiz", demo: "appgrid", label: "Super AMOLED",
    eli5: "Super AMOLED. Thin enough to vanish.",
    specs: ["Super AMOLED Plus", "8.5 mm thin", "Dual-core"],
    materials: "Feather-light plastic that vaulted Samsung." },
  { id: "2011-iphone4s", year: 2011, name: "iPhone 4S", era: "smartphone", chapter: "glass",
    feature: "siri", demo: "siri", label: "Hello, Siri",
    eli5: "The phone talks back. Ask it something.",
    specs: ["Siri assistant", "8 MP camera", "Dual-core A5"],
    materials: "Same glass icon — now it answers." },
  { id: "2012-galaxy-s3", year: 2012, name: "Samsung Galaxy S III", era: "android", chapter: "everyone",
    feature: "home_softkeys", demo: "appgrid", label: "Designed for humans",
    eli5: "Pebble blue. Everyone got a smartphone.",
    specs: ["Pebble-blue shell", "S Voice", "Pop-up play"],
    materials: "Organic curves in glossy hyperglaze." },
  { id: "2012-lumia920", year: 2012, name: "Nokia Lumia 920", era: "wp8", chapter: "everyone",
    feature: "live_tiles", demo: "live_tiles", label: "Live Tiles",
    eli5: "Tiles that actually live. Tap one.",
    specs: ["Windows Phone 8", "PureView OIS", "Wireless charging"],
    materials: "Bold polycarbonate in cyan and yellow." },
  { id: "2013-iphone5s", year: 2013, name: "iPhone 5s", era: "smartphone", chapter: "everyone",
    feature: "touch_id", demo: "touch_id", label: "Touch ID",
    eli5: "Your fingerprint is the key. Press home.",
    specs: ["Touch ID sensor", "64-bit A7", "Slow-mo camera"],
    materials: "Anodised aluminium — press to unlock." },
  { id: "2013-nexus5", year: 2013, name: "Nexus 5", era: "android", chapter: "everyone",
    feature: "kitkat_pure", demo: "appgrid", label: "Pure KitKat",
    eli5: "Stock Android. Nothing in the way.",
    specs: ["Stock Android 4.4", "Soft-touch back", "Great value"],
    materials: "Matte black — Google's clean reference." },
  { id: "2014-iphone6", year: 2014, name: "iPhone 6", era: "smartphone", chapter: "everyone",
    feature: "larger_display", demo: "size_grow", label: "It got bigger",
    eli5: "It got bigger. That was the news.",
    specs: ["4.7-inch display", "Rounded aluminium", "Apple Pay"],
    materials: "Slim curved-glass unibody." },
  { id: "2014-note4", year: 2014, name: "Galaxy Note 4", era: "phablet", chapter: "everyone",
    feature: "s_pen", demo: "spen", label: "The S Pen",
    eli5: "A phone with a pen. Scribble.",
    specs: ["S Pen stylus", "Quad-HD AMOLED", "Metal frame"],
    materials: "Faux-leather back + stylus." },
  { id: "2015-iphone6s", year: 2015, name: "iPhone 6s", era: "smartphone", chapter: "everyone",
    feature: "3d_touch", demo: "force_touch", label: "3D Touch",
    eli5: "Press harder. The glass can feel it.",
    specs: ["3D Touch", "7000 aluminium", "Live Photos"],
    materials: "Press-sensitive glass — peek." },
  { id: "2015-mate8", year: 2015, name: "Huawei Mate 8", era: "android", chapter: "everyone",
    feature: "big_battery", demo: "battery", label: "All-day battery",
    eli5: "A battery that lasts two days.",
    specs: ["4000 mAh battery", "Kirin 950", "Metal unibody"],
    materials: "Big-screen metal built to last." },
  { id: "2016-pixel", year: 2016, name: "Google Pixel", era: "android", chapter: "everyone",
    feature: "assistant", demo: "assistant", label: "Google Assistant",
    eli5: "Hey Google. Assistant, built in.",
    specs: ["Google Assistant", "Best-in-class camera", "Two-tone glass"],
    materials: "Aluminium with a glass shade." },
  { id: "2016-iphone7", year: 2016, name: "iPhone 7", era: "smartphone", chapter: "everyone",
    feature: "no_headphone_jack", demo: "no_jack", label: "Courage",
    eli5: "They killed the headphone jack. Courage.",
    specs: ["No headphone jack", "Water resistant", "Taptic home button"],
    materials: "Jet-black aluminium. The 3.5 mm takes a bow." },
  { id: "2017-iphone-x", year: 2017, name: "iPhone X", era: "notch", chapter: "edge",
    feature: "face_id_notch", demo: "face_id", label: "The notch + Face ID",
    eli5: "No home button. Glance to unlock.",
    specs: ["Edge-to-edge OLED", "Face ID", "No home button"],
    materials: "Surgical steel + glass." },
  { id: "2017-note8", year: 2017, name: "Galaxy Note 8", era: "android", chapter: "edge",
    feature: "dual_camera", demo: "camera_lenses", label: "Dual camera",
    eli5: "Two cameras. Pick a lens.",
    specs: ["Dual 12 MP", "Infinity Display", "S Pen"],
    materials: "Glass-and-metal phablet." },
  { id: "2018-essential", year: 2018, name: "Essential Phone", era: "android", chapter: "edge",
    feature: "ceramic_notch", demo: "face_id", label: "Tiny notch",
    eli5: "Almost no bezel. Almost.",
    specs: ["Ceramic + titanium", "Edge-to-edge", "Magnetic mods"],
    materials: "Andy Rubin's near-bezel-less ceramic slab." },
  { id: "2018-mate20pro", year: 2018, name: "Huawei Mate 20 Pro", era: "android", chapter: "edge",
    feature: "in_display_fp", demo: "underdisplay_fp", label: "Under-glass print",
    eli5: "Fingerprint under the glass. Press it.",
    specs: ["In-display fingerprint", "Triple Leica cam", "Curved OLED"],
    materials: "Gradient glass." },
  { id: "2019-fold", year: 2019, name: "Samsung Galaxy Fold", era: "foldable", chapter: "edge",
    feature: "fold_open", demo: "fold", label: "It folds",
    eli5: "A phone that becomes a tablet. Unfold it.",
    specs: ["Foldable OLED", "Book fold", "Six cameras"],
    materials: "First mainstream folding phone." },
  { id: "2019-iphone11", year: 2019, name: "iPhone 11 Pro", era: "triple_cam", chapter: "edge",
    feature: "triple_camera", demo: "camera_lenses", label: "Triple camera",
    eli5: "Three cameras. Night mode.",
    specs: ["Triple 12 MP", "Matte glass", "Night mode"],
    materials: "Frosted glass, triangle bump." },
  { id: "2020-iphone12", year: 2020, name: "iPhone 12", era: "5g", chapter: "edge",
    feature: "magSafe", demo: "magsafe", label: "MagSafe snap",
    eli5: "Magnets in the back. Snap the puck.",
    specs: ["5G", "MagSafe magnets", "Flat ceramic-shield edges"],
    materials: "Flat-edged aluminium." },
  { id: "2020-pixel5", year: 2020, name: "Pixel 5", era: "android", chapter: "edge",
    feature: "pure_android", demo: "appgrid", label: "Clean Android",
    eli5: "Clean Android in recycled metal.",
    specs: ["Bio-resin body", "5G", "Rear fingerprint"],
    materials: "Recycled-aluminium sage." },
  { id: "2021-zfold3", year: 2021, name: "Galaxy Z Fold 3", era: "foldable", chapter: "edge",
    feature: "fold_s_pen", demo: "fold", label: "Fold + S Pen",
    eli5: "Fold, then write on it.",
    specs: ["Under-display camera", "S Pen support", "IPX8 water resist"],
    materials: "Refined book-fold, hidden camera." },
  { id: "2021-iphone13pro", year: 2021, name: "iPhone 13 Pro", era: "pro", chapter: "edge",
    feature: "pro_motion", demo: "promotion", label: "120 Hz ProMotion",
    eli5: "120 Hz. Watch the smoothness change.",
    specs: ["120 Hz ProMotion", "Cinematic mode", "Surgical steel"],
    materials: "Sierra-blue glass." },
  { id: "2022-iphone14pro", year: 2022, name: "iPhone 14 Pro", era: "island", chapter: "island",
    feature: "dynamic_island", demo: "dynamic_island", label: "Dynamic Island",
    eli5: "The notch becomes a living pill. Tap it.",
    specs: ["Dynamic Island", "Always-on display", "48 MP main"],
    materials: "The pill that lives at the top of the glass." },
  { id: "2022-pixel7pro", year: 2022, name: "Pixel 7 Pro", era: "android", chapter: "island",
    feature: "tensor_cam", demo: "camera_lenses", label: "Tensor camera",
    eli5: "Tensor looks at the photo. Switch a lens.",
    specs: ["Tensor G2", "Camera bar", "Magic Eraser"],
    materials: "Polished-aluminium visor." },
  { id: "2023-zflip5", year: 2023, name: "Galaxy Z Flip 5", era: "flip_fold", chapter: "island",
    feature: "cover_screen", demo: "flip_fold", label: "Flip + cover screen",
    eli5: "A cover screen on a pocket square.",
    specs: ["Big cover screen", "Flex hinge", "Compact fold"],
    materials: "Pocket square that flips shut." },
  { id: "2023-iphone15pro", year: 2023, name: "iPhone 15 Pro", era: "usb_c", chapter: "island",
    feature: "action_button", demo: "action_button", label: "Action Button + USB-C",
    eli5: "Titanium. One new button. Press it.",
    specs: ["Titanium frame", "Action Button", "USB-C"],
    materials: "Brushed titanium." },
  { id: "2024-pixel9pro", year: 2024, name: "Pixel 9 Pro", era: "android", chapter: "island",
    feature: "gemini", demo: "assistant", label: "Gemini AI",
    eli5: "Gemini lives on the phone. Ask it.",
    specs: ["Gemini assistant", "Flat frame", "Pill camera bar"],
    materials: "Matte-glass flagship, on-device AI." },
  { id: "2025-iphone16pro", year: 2025, name: "iPhone 16 Pro", era: "apple", chapter: "island",
    feature: "camera_control", demo: "camera_control", label: "Camera Control",
    eli5: "A slider just for the camera. Drag it.",
    specs: ["Camera Control slider", "A18 Pro", "Larger displays"],
    materials: "Titanium Pro." },
  { id: "2026-foldable", year: 2026, name: "2026 Flagship Fold", era: "foldable", chapter: "island",
    feature: "thin_fold", demo: "fold", label: "The thin fold",
    eli5: "The crease is almost gone. Unfold what's next.",
    specs: ["Crease-free fold", "Ultra-thin", "AI everywhere"],
    materials: "A near-seamless folding slab." }
];
