// Canonical 50 phones (1992-2026). Base ids/years/names/era/feature come from
// PHONES-50.json; each entry is enriched with a short label, 2-4 key specs,
// a materials note, and the interactive demo used for its signature feature.
window.PHONES = [
  { id: "1992-microtac", year: 1992, name: "Motorola MicroTAC", era: "brick", feature: "flip_mouthpiece",
    label: "The flip is born", demo: "flip_mouthpiece",
    specs: ["Flip-down mouthpiece", "Red LED display", "Nickel-cadmium battery"],
    materials: "Charcoal ABS plastic, pull-up antenna, first truly pocketable cellphone." },
  { id: "1996-starTAC", year: 1996, name: "Motorola StarTAC", era: "flip", feature: "clamshell",
    label: "First clamshell", demo: "clamshell",
    specs: ["Clamshell fold", "Vibrate alert", "~88 g"],
    materials: "Magnesium-grey shell, the phone that made 'flip' a status symbol." },
  { id: "1999-3310", year: 1999, name: "Nokia 3310", era: "candybar", feature: "snake",
    label: "Indestructible", demo: "snake",
    specs: ["Snake II", "Xpress-on covers", "Monochrome LCD"],
    materials: "Bombproof polycarbonate; 126 million sold. Play Snake below." },
  { id: "2000-6210", year: 2000, name: "Nokia 6210", era: "candybar", feature: "sms",
    label: "Texting machine", demo: "t9",
    specs: ["T9 predictive text", "WAP browser", "Infrared"],
    materials: "Slim dark-green candybar; the business texter's favourite." },
  { id: "2002-3650", year: 2002, name: "Nokia 3650", era: "candybar", feature: "camera_circle_pad",
    label: "Circular keypad", demo: "rotary_keys",
    specs: ["Built-in camera", "Rotary keypad", "Symbian S60"],
    materials: "Playful pod shape with an unmistakable round dial keypad." },
  { id: "2002-treo", year: 2002, name: "Palm Treo 180", era: "pda", feature: "stylus",
    label: "PDA meets phone", demo: "stylus",
    specs: ["Palm OS", "QWERTY thumbboard", "Stylus + touch"],
    materials: "Grey PDA-phone hybrid; tap the resistive screen with a stylus." },
  { id: "2003-6600", year: 2003, name: "Nokia 6600", era: "candybar", feature: "symbian",
    label: "Symbian smartphone", demo: "appgrid",
    specs: ["Symbian S60", "VGA camera", "65k colour screen"],
    materials: "Rounded pebble; an early app-running smartphone for the masses." },
  { id: "2004-razr", year: 2004, name: "Motorola RAZR V3", era: "flip", feature: "flip_animation",
    label: "Impossibly thin", demo: "flip_animation",
    specs: ["14 mm thin", "Etched metal keypad", "Anodised aluminium"],
    materials: "Aircraft-aluminium icon of the mid-2000s. Flip it open." },
  { id: "2004-n-gage", year: 2004, name: "Nokia N-Gage", era: "gaming", feature: "side_talk",
    label: "Game deck phone", demo: "sidetalk",
    specs: ["Game cartridges", "Side-talking", "Symbian S60"],
    materials: "The 'taco' gaming phone you held sideways to your ear." },
  { id: "2005-sidekick", year: 2005, name: "T-Mobile Sidekick II", era: "slider", feature: "swing_screen",
    label: "Swivel screen", demo: "swing_screen",
    specs: ["Swivel display", "QWERTY", "Always-on data"],
    materials: "Beloved by texters; flick the screen to reveal the keyboard." },
  { id: "2006-chocolate", year: 2006, name: "LG Chocolate", era: "slider", feature: "slide_keys",
    label: "Touch-glow slider", demo: "slider",
    specs: ["Touch-sensitive keys", "Slide-up form", "Music focus"],
    materials: "Glossy black slab with red glowing capacitive controls." },
  { id: "2006-n95", year: 2006, name: "Nokia N95", era: "slider", feature: "slide_camera",
    label: "Multimedia computer", demo: "twoway_slider",
    specs: ["5 MP Carl Zeiss", "Two-way slide", "GPS + Wi-Fi"],
    materials: "Dual-slider powerhouse: media keys up, keypad down." },
  { id: "2007-iphone", year: 2007, name: "iPhone (1st gen)", era: "smartphone", feature: "homescreen",
    label: "Multitouch begins", demo: "springboard",
    specs: ["Multitouch glass", "One home button", "Visual voicemail"],
    materials: "Aluminium + glass. Tap the SpringBoard icons below." },
  { id: "2007-curve", year: 2007, name: "BlackBerry Curve 8300", era: "qwerty", feature: "trackball_bbm",
    label: "Trackball + BBM", demo: "bbm",
    specs: ["Pearl trackball", "Full QWERTY", "Push email"],
    materials: "The messaging machine. Send a BBM and watch the D/R ticks." },
  { id: "2008-g1", year: 2008, name: "HTC Dream (G1)", era: "android", feature: "slide_qwerty",
    label: "First Android", demo: "slide_qwerty",
    specs: ["Android 1.0", "Slide QWERTY", "Trackball"],
    materials: "The very first Android phone; slide out the keyboard." },
  { id: "2008-bold", year: 2008, name: "BlackBerry Bold 9000", era: "qwerty", feature: "optical_trackpad",
    label: "Business icon", demo: "bbm",
    specs: ["Sharp QWERTY", "Leatherette back", "3G + Wi-Fi"],
    materials: "Chrome-framed status symbol of the boardroom." },
  { id: "2009-pre", year: 2009, name: "Palm Pre", era: "webos", feature: "card_multitask",
    label: "Cards multitasking", demo: "webos_cards",
    specs: ["webOS", "Card multitasking", "Slide keyboard"],
    materials: "Pebble-smooth webOS phone; swipe cards to multitask." },
  { id: "2009-droid", year: 2009, name: "Motorola Droid", era: "android", feature: "slide_keyboard",
    label: "Droid does", demo: "slide_qwerty",
    specs: ["Android 2.0", "Slide keyboard", "Google Maps Nav"],
    materials: "Industrial slab of metal that made Android mainstream in the US." },
  { id: "2010-iphone4", year: 2010, name: "iPhone 4", era: "smartphone", feature: "retina_homescreen",
    label: "Retina display", demo: "springboard",
    specs: ["Retina display", "Stainless frame", "FaceTime"],
    materials: "Glass sandwich on a steel band; pixels you couldn't see." },
  { id: "2010-n8", year: 2010, name: "Nokia N8", era: "symbian", feature: "xenon_flash",
    label: "Xenon camera", demo: "camera_shutter",
    specs: ["12 MP Xenon flash", "HDMI out", "Anodised aluminium"],
    materials: "Candy-coloured metal unibody with a real Xenon flash. Snap a photo." },
  { id: "2010-desire", year: 2010, name: "HTC Desire", era: "android", feature: "sense_ui",
    label: "HTC Sense", demo: "appgrid",
    specs: ["HTC Sense UI", "AMOLED screen", "Optical trackpad"],
    materials: "Soft-touch Android favourite with a flip-clock home screen." },
  { id: "2011-galaxy-s2", year: 2011, name: "Samsung Galaxy S II", era: "android", feature: "touchwiz",
    label: "Super AMOLED", demo: "appgrid",
    specs: ["Super AMOLED Plus", "8.5 mm thin", "Dual-core"],
    materials: "Feather-light plastic that vaulted Samsung to the top." },
  { id: "2011-iphone4s", year: 2011, name: "iPhone 4S", era: "smartphone", feature: "siri",
    label: "Hello, Siri", demo: "siri",
    specs: ["Siri assistant", "8 MP camera", "Dual-core A5"],
    materials: "Same glass icon, now it talks back. Ask Siri something." },
  { id: "2012-galaxy-s3", year: 2012, name: "Samsung Galaxy S III", era: "android", feature: "home_softkeys",
    label: "Designed for humans", demo: "appgrid",
    specs: ["Pebble-blue shell", "S Voice", "Pop-up play"],
    materials: "Organic curves in glossy 'hyperglaze' polycarbonate." },
  { id: "2012-lumia920", year: 2012, name: "Nokia Lumia 920", era: "wp8", feature: "live_tiles",
    label: "Live Tiles", demo: "live_tiles",
    specs: ["Windows Phone 8", "PureView OIS", "Wireless charging"],
    materials: "Bold polycarbonate in cyan/yellow. Watch the Live Tiles flip." },
  { id: "2013-iphone5s", year: 2013, name: "iPhone 5s", era: "smartphone", feature: "touch_id",
    label: "Touch ID", demo: "touch_id",
    specs: ["Touch ID sensor", "64-bit A7", "Slow-mo camera"],
    materials: "Anodised aluminium; press the home button to unlock." },
  { id: "2013-nexus5", year: 2013, name: "Nexus 5", era: "android", feature: "kitkat_pure",
    label: "Pure KitKat", demo: "appgrid",
    specs: ["Stock Android 4.4", "Soft-touch back", "Great value"],
    materials: "Matte black slab; Google's clean Android reference." },
  { id: "2014-iphone6", year: 2014, name: "iPhone 6", era: "smartphone", feature: "larger_display",
    label: "It got bigger", demo: "size_grow",
    specs: ["4.7-inch display", "Rounded aluminium", "Apple Pay"],
    materials: "Slim curved-glass unibody; Apple finally went big." },
  { id: "2014-note4", year: 2014, name: "Galaxy Note 4", era: "phablet", feature: "s_pen",
    label: "The S Pen", demo: "spen",
    specs: ["S Pen stylus", "Quad-HD AMOLED", "Metal frame"],
    materials: "Faux-leather back + stylus. Scribble a note below." },
  { id: "2015-iphone6s", year: 2015, name: "iPhone 6s", era: "smartphone", feature: "3d_touch",
    label: "3D Touch", demo: "force_touch",
    specs: ["3D Touch", "7000 aluminium", "Live Photos"],
    materials: "Press-sensitive glass; push hard to peek." },
  { id: "2015-mate8", year: 2015, name: "Huawei Mate 8", era: "android", feature: "big_battery",
    label: "All-day battery", demo: "battery",
    specs: ["4000 mAh battery", "Kirin 950", "Metal unibody"],
    materials: "Big-screen metal phone built to last two days." },
  { id: "2016-pixel", year: 2016, name: "Google Pixel", era: "android", feature: "assistant",
    label: "Google Assistant", demo: "assistant",
    specs: ["Google Assistant", "Best-in-class camera", "Two-tone glass"],
    materials: "Aluminium with a glass shade; Google's own phone arrives." },
  { id: "2016-iphone7", year: 2016, name: "iPhone 7", era: "smartphone", feature: "no_headphone_jack",
    label: "Courage", demo: "no_jack",
    specs: ["No headphone jack", "Water resistant", "Taptic home button"],
    materials: "Jet-black aluminium; the 3.5 mm jack takes its bow." },
  { id: "2017-iphone-x", year: 2017, name: "iPhone X", era: "notch", feature: "face_id_notch",
    label: "The notch + Face ID", demo: "face_id",
    specs: ["Edge-to-edge OLED", "Face ID", "No home button"],
    materials: "Surgical-steel + glass; glance to unlock with Face ID." },
  { id: "2017-note8", year: 2017, name: "Galaxy Note 8", era: "android", feature: "dual_camera",
    label: "Dual camera", demo: "camera_lenses",
    specs: ["Dual 12 MP", "Infinity Display", "S Pen"],
    materials: "Glass-and-metal phablet; switch between the two lenses." },
  { id: "2018-essential", year: 2018, name: "Essential Phone", era: "android", feature: "ceramic_notch",
    label: "Tiny notch", demo: "face_id",
    specs: ["Ceramic + titanium", "Edge-to-edge", "Magnetic mods"],
    materials: "Andy Rubin's near-bezel-less ceramic slab." },
  { id: "2018-mate20pro", year: 2018, name: "Huawei Mate 20 Pro", era: "android", feature: "in_display_fp",
    label: "Under-glass print", demo: "underdisplay_fp",
    specs: ["In-display fingerprint", "Triple Leica cam", "Curved OLED"],
    materials: "Gradient glass; press the on-screen fingerprint to unlock." },
  { id: "2019-fold", year: 2019, name: "Samsung Galaxy Fold", era: "foldable", feature: "fold_open",
    label: "It folds", demo: "fold",
    specs: ["Foldable OLED", "Book fold", "Six cameras"],
    materials: "First mainstream folding phone. Unfold it into a tablet." },
  { id: "2019-iphone11", year: 2019, name: "iPhone 11 Pro", era: "triple_cam", feature: "triple_camera",
    label: "Triple camera", demo: "camera_lenses",
    specs: ["Triple 12 MP", "Matte glass", "Night mode"],
    materials: "Frosted glass with the iconic camera-bump triangle." },
  { id: "2020-iphone12", year: 2020, name: "iPhone 12", era: "5g", feature: "magSafe",
    label: "MagSafe snap", demo: "magsafe",
    specs: ["5G", "MagSafe magnets", "Flat ceramic-shield edges"],
    materials: "Flat-edged aluminium; snap a MagSafe puck to the back." },
  { id: "2020-pixel5", year: 2020, name: "Pixel 5", era: "android", feature: "pure_android",
    label: "Clean Android", demo: "appgrid",
    specs: ["Bio-resin body", "5G", "Rear fingerprint"],
    materials: "Recycled-aluminium 'sage' phone with pure Android." },
  { id: "2021-zfold3", year: 2021, name: "Galaxy Z Fold 3", era: "foldable", feature: "fold_s_pen",
    label: "Fold + S Pen", demo: "fold",
    specs: ["Under-display camera", "S Pen support", "IPX8 water resist"],
    materials: "Refined book-fold with a hidden selfie camera." },
  { id: "2021-iphone13pro", year: 2021, name: "iPhone 13 Pro", era: "pro", feature: "pro_motion",
    label: "120 Hz ProMotion", demo: "promotion",
    specs: ["120 Hz ProMotion", "Cinematic mode", "Surgical steel"],
    materials: "Sierra-blue glass; drag to feel the smooth 120 Hz." },
  { id: "2022-iphone14pro", year: 2022, name: "iPhone 14 Pro", era: "island", feature: "dynamic_island",
    label: "Dynamic Island", demo: "dynamic_island",
    specs: ["Dynamic Island", "Always-on display", "48 MP main"],
    materials: "The notch becomes a shape-shifting pill. Tap it." },
  { id: "2022-pixel7pro", year: 2022, name: "Pixel 7 Pro", era: "android", feature: "tensor_cam",
    label: "Tensor camera", demo: "camera_lenses",
    specs: ["Tensor G2", "Camera bar", "Magic Eraser"],
    materials: "Polished-aluminium visor across a glossy glass back." },
  { id: "2023-zflip5", year: 2023, name: "Galaxy Z Flip 5", era: "flip_fold", feature: "cover_screen",
    label: "Flip + cover screen", demo: "flip_fold",
    specs: ["Big cover screen", "Flex hinge", "Compact fold"],
    materials: "Pocket square that flips shut. Fold and use the cover screen." },
  { id: "2023-iphone15pro", year: 2023, name: "iPhone 15 Pro", era: "usb_c", feature: "action_button",
    label: "Action Button + USB-C", demo: "action_button",
    specs: ["Titanium frame", "Action Button", "USB-C"],
    materials: "Brushed titanium; toggle the new Action Button." },
  { id: "2024-pixel9pro", year: 2024, name: "Pixel 9 Pro", era: "android", feature: "gemini",
    label: "Gemini AI", demo: "assistant",
    specs: ["Gemini assistant", "Flat frame", "Pill camera bar"],
    materials: "Matte-glass flagship built around on-device AI." },
  { id: "2025-iphone16pro", year: 2025, name: "iPhone 16 Pro", era: "apple", feature: "camera_control",
    label: "Camera Control", demo: "camera_control",
    specs: ["Camera Control slider", "A18 Pro", "Larger displays"],
    materials: "Titanium Pro; slide along the new capacitive Camera Control." },
  { id: "2026-foldable", year: 2026, name: "2026 Flagship Fold", era: "foldable", feature: "thin_fold",
    label: "The thin fold", demo: "fold",
    specs: ["Crease-free fold", "Ultra-thin", "AI everywhere"],
    materials: "A near-seamless folding slab — where the timeline points next." }
];
